### PR TITLE
Completed Hindi translation.

### PR DESCRIPTION
**Pull request by G0v1ndD3v**
Add translated strings and arrays for Hindi localization in XML.

### CODE REVIEW

**Comment by G0v1ndD3v** [comment]
**Note:** For well-known terms like 'Light' and 'Dark' mode, I used their Hindi transliterations ('लाईट', 'डार्क') to maintain familiarity for users. For words where a direct translation might not exist or feel natural, I have chosen to explain their meaning instead (e.g., 'custom' - 'पसंद के अनुसार,' meaning 'as per your choice').

**Comment by hajdam** [comment]
Please rename "values - hi" to "values-hi" (drop spaces), preferably with "git mv" command or Git GUI tool.
Language entries should be kept only in main language, but I can fix it myself.

**Comment by hajdam** [comment]
I'll rename the directory afterwards.

**Comment by G0v1ndD3v** [comment]
> Please rename "values - hi" to "values-hi" (drop spaces), preferably with "git mv" command or Git GUI tool. Language entries should be kept only in main language, but I can fix it myself.

Ah, my bad! I’ll keep that in mind for next time. Thank you!

**Pull request merged**
